# Generated by Django 3.0.8 on 2020-08-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='init_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
